language: node_js
node_js:
- node
notifications:
  email: false
deploy:
  provider: heroku
  api_key:
    secure: gh4M805UggCxmcUOJxmONVUIzIfpserpQQsK2DRX1RC/RSyk/W9YfMHx/+YEABNLKxNpMcTOQYyylDo2Ad31ujzHfFNswYLiToGNaPRZshrAKbhNjJBn3CGudg62yiGhWsyzRQqD/r+DFZ0XoO0C8p5X7Lxs4JfEmwqcZiJh/5E7jpGH5amqNK/Y6nZjWiyJsmOPbxqtt2vyskaZbMwLokV3tXmOjeOE7iXKePixQeVCguIVhp6IxOzXW0cUquIWmvu8kaYPXRcxWfwNTAHrZgwQ0u2vIPi8MjyfUfJ2T3HOCoGgB5Q+10uP6FgW1ny+hhGv4n2fxxjtDzPRjO85L9pVHASnsE5VOAtWW2zuy66I9fVTihVW7wlJs9QXuzlc4G+aVZofKvHXPYTqJI6BYjw46TnYWz5FmRJxClO2X9qOt7WwsTjbamLcpjs99t/KXRFg0iu0ct+V+NS7uFXZHIosIOcTCi2uLraUEz1tzenWf8Zl6s/R3lTXk/Q83HG5kiMyxdbiVoDdf+HOJm6uDMW1Fb+slvY9Y5YqQlbww+65aaE2F0oa96xka3Vv/MZIKJSMc0qaCXoL9yoM5EU8S3SFCnmbKXuJZt48iw2nu/DQwkzUpHpPQuOf4SFnxaLL46E+kMIwHIsHbeCpF6jhs6XDNnS4s4u8RluCtP1dc8o=
  app: vacation-rentals-around-denver
  skip_cleanup: true